Homework7
MykytaKh/Fortune-teller-App pull request #11
Opened 2021-11-26 09:59 UTC by MykytaKh

● used Realm as local answers storage
● added new feature - answers history. Any loaded answer should be stored with text and date timestamp. Embed main screen and this new screen in UITabBarController. Display answers on separate screen, use sorting “the newest first”. Used all available in storage answers as answers for offline mode.
● “Wrapped” Realm in separate persistent service.

2021-11-28 14:30 UTC, ios-school-yalantis requested changes
Просмотрел, Нужны чейнджы!
Пиши если что в телеграм, постараюсь ответить!

2021-11-28 14:30 UTC, ios-school-yalantis commented on 8-Ball/8-Ball/Services/RealmService.swift
> +class RealmService: Object {
плохое название для Entity

2021-11-28 14:30 UTC, ios-school-yalantis commented on 8-Ball/8-Ball/Flows/History/AnswersHistoryVC.swift
> +import RealmSwift
тут не должно быть import RealmSwift
вся логика должны быть скрыта в DBService

2021-11-28 14:30 UTC, ios-school-yalantis commented on 8-Ball/8-Ball/Flows/History/AnswersHistoryVC.swift
> +    var answers: Results<RealmService>!
данные должны идти из model -> viewModel

удалить var answers: Results<RealmService>!

2021-11-28 14:30 UTC, ios-school-yalantis commented on 8-Ball/8-Ball/Flows/History/AnswersHistoryModel.swift
> +import RealmSwift
не должно быть импорта RealmSwift

2021-11-28 14:30 UTC, ios-school-yalantis commented on 8-Ball/8-Ball/Flows/History/AnswersHistoryModel.swift
> +            return randomObjectName
логика извлечения должна быть скрыта внутри сервиса и возвращать не рилмовские объекты

2021-11-28 14:30 UTC, ios-school-yalantis commented on 8-Ball/8-Ball/Flows/History/AnswersHistoryModel.swift
> +            return answers
same

2021-11-28 14:30 UTC, ios-school-yalantis commented on 8-Ball/8-Ball/Flows/Answers/LocalDefaultAnswerModel.swift
> +                                "Very doubtful"]
Можно в момент загрузки приложения проверять если это первый запуск, то записывать локальные ответы в рилм

к объекту добавть параметр isLocal: Bool по которому можно будет отличить локальный это ответ или нет, таким образов избавимся от ненужной зависимости и все данные буду возвращаться через рилм

2021-11-28 14:30 UTC, ios-school-yalantis commented on 8-Ball/8-Ball/Flows/Answers/AnswerModel.swift
> +import RealmSwift
не должно быть импорта RealmService

логика должна быть построена таким образом что бы в любой момент можно было заменить на кор дату не меня уже реализованный код

2021-11-28 16:16 UTC, MykytaKh commented
Спасибо. Исправил.

2021-11-29 12:49 UTC, ios-school-yalantis requested changes
Нужно переделать BataBaseService разделить ответственности (убрать хранение данных из него и наследование от Object)

Добавить ManagedAnswer: Object и манипулировать ими внутри сервиса
внаружу должны быть использованы толко Answer struct.

2021-11-29 12:49 UTC, ios-school-yalantis commented on 8-Ball/8-Ball/Services/DataBaseService.swift
> +}
Нужно разделить логику от данных DataBaseService занимается  CRUD операциями. То есть DataBaseService хранить данные. 

Нужно добавить ManagedAnswer и манипулировать им внутри DataBaseService.

Сейчас же DataBaseService это рилмовский объект который умеет вытаскивать себе подобные объекты, он не должен уметь этого делать (принцип единой отвецвтености) он только предоставляет данные.  DataBaseService должен заниматься  CRUD операциями над этими объектами.

2021-11-29 16:03 UTC, MykytaKh commented
Исправил

2021-11-29 17:56 UTC, ios-school-yalantis approved these changes
Исправь плз комменты и можно мерджить

2021-11-29 17:56 UTC, ios-school-yalantis commented on 8-Ball/8-Ball/Services/DataBaseService.swift
> +    var answers: Results<ManagedAnswer>!
а для чего тут эта переменная? не вижу в ней смысла, все объекты вытаскиваются из рилма

2021-11-29 17:56 UTC, ios-school-yalantis commented on 8-Ball/8-Ball/Services/DataBaseService.swift
>      func deleteAnswer(index: Int) {
не очень хороший подход удалять по индексу в базе)

лучше как параметр передавать Answer структуру, фетчить объект из базы и удалять его!

2021-11-29 17:56 UTC, ios-school-yalantis commented on 8-Ball/8-Ball/Services/DataBaseService.swift
>      func getRandomAnswer() -> String? {
так же лучше реализовать что бы работать не с стругами, а с Answer struct

2021-11-29 17:56 UTC, ios-school-yalantis commented on 8-Ball/8-Ball/Services/DataBaseService.swift
> +    func getAnswers() -> [ManagedAnswer] {
возвращай сразу Answer struct

2021-11-29 17:56 UTC, ios-school-yalantis commented on 8-Ball/8-Ball/Services/DataBaseService.swift
>      func addAnswer(answer: String) {
работай с answer struct

2021-11-29 17:56 UTC, ios-school-yalantis commented on 8-Ball/8-Ball/Flows/History/AnswersHistoryVC.swift
> +    var answers: [ManagedAnswer] {
рилмовские объекты должны быть скрыты внутри DBService 
используем только Answer struct

2021-11-29 17:56 UTC, ios-school-yalantis commented on 8-Ball/8-Ball/Flows/History/AnswersHistoryVM.swift
> +    func getAnswers() -> [ManagedAnswer] {
same

2021-11-29 17:56 UTC, ios-school-yalantis commented on 8-Ball/8-Ball/Flows/History/AnswersHistoryModel.swift
> +    func getAnswers() -> [ManagedAnswer] {
same

2021-12-05 22:54 UTC, merged