homework11
MykytaKh/Fortune-teller-App pull request #15
Opened 2021-12-19 22:36 UTC by MykytaKh

Added NavigationNode
Used FlowCoordinator
Filled in README.md

2021-12-21 18:38 UTC, ios-school-yalantis requested changes

2021-12-21 18:38 UTC, ios-school-yalantis commented on 8-Ball/8-Ball/Delegates/SceneDelegate.swift
> +        let flowCoordinator = TabBarCoordinator(navigationController: navigationController)
обычно UINavigationController лежат внутри TabBar.  и лучше всего в TabBarCoordinator в ините передавать window и туда как рут в методе start() присваивать туда таб бар контроллер

2021-12-21 18:38 UTC, ios-school-yalantis commented on 8-Ball/8-Ball/FlowCoordinators/SettingsCoordinator.swift
> +class SettingsCoordinator {
координаторы должны наследоваться от FlowCoordinator и NavigationNode и в функции createFlow() возвращать начальный контроллер

2021-12-21 18:38 UTC, ios-school-yalantis commented on 8-Ball/8-Ball/Flows/CustomTabBarController.swift
> +        let settingsCoordRoot = settingsCoordinator.containerViewController
вот тут везде вместо containerViewController должны присваиваться контроллеры из createFlow()

2021-12-22 21:09 UTC, MykytaKh commented
Спасибо за пример, постарался изменить по примеру.

2022-01-04 13:41 UTC, merged