Homework 2
MykytaKh/Fortune-teller-App pull request #5
Opened 2021-11-09 11:33 UTC by MykytaKh

Refactored project according to SOLID principles. 
Removed DB and API logic from ViewController - created separate objects for API and DB logic. 
Added abstractions for API and DB. 
Added `private` wherever it is possible. 
Used Dependency Injection.

2021-11-09 19:34 UTC, ios-school-yalantis requested changes

2021-11-09 19:34 UTC, ios-school-yalantis commented on 8-Ball/8-Ball/AnswerManager.swift
> +        self.dbService = DBService()
зависимости должны быть переданы извне

2021-11-09 19:34 UTC, ios-school-yalantis commented on 8-Ball/8-Ball/Network.swift
> +    }
тут правильнее будет передать зависимость в инициализаторе, но URLSession.shared и так шаред, по этому можно сделать значение по умолчанию итого что-то типа 
```
init(urlSession: URLSession = URLSession.shared) {
         self.urlString = "https://8ball.delegator.com/magic/JSON/question_string"
         self.urlSession = urlSession
 }
 ```

2021-11-09 19:34 UTC, ios-school-yalantis commented on 8-Ball/8-Ball/SettingsVC.swift
> +    private let dbService = DBService()
зависимости должны быть переданы из вне

2021-11-09 19:34 UTC, ios-school-yalantis commented on 8-Ball/8-Ball/ViewController.swift
> +    private let answerManager = AnswerManager()
также нужно из вне

2021-11-10 20:31 UTC, MykytaKh commented
Спасибо. Пофиксил. Проверьте пожалуйста.

2021-11-11 09:05 UTC, ios-school-yalantis requested changes

2021-11-11 09:05 UTC, ios-school-yalantis commented on 8-Ball/8-Ball/ViewController.swift
> +            let answerManager = AnswerManager(networkService: Network(), dbService: DBService())
AnswerManager нужно передать контроллеру извне

2021-11-11 19:09 UTC, MykytaKh commented
Пофиксил. Проверьте пожалуйста.

2021-11-11 19:21 UTC, ios-school-yalantis requested changes

2021-11-11 19:21 UTC, ios-school-yalantis commented on 8-Ball/8-Ball/SceneDelegate.swift
> +        }
так может работать, но подход не надежный, правильно будет создать контроллер и добавить его на экран

2021-11-11 20:02 UTC, MykytaKh commented
Изменил.

2021-11-12 09:21 UTC, ios-school-yalantis approved these changes
все хорошо, можно мержить

2021-11-12 10:30 UTC, merged