Homework4
MykytaKh/Fortune-teller-App pull request #7
Opened 2021-11-16 21:38 UTC by MykytaKh

Useв MVVM with active model in my project.

2021-11-17 11:47 UTC, ios-school-yalantis requested changes
- Добавлен Alamofire  но не используется, нужно избавится от лишних зависимостей.
- Нужно реализовать для каждого экрана model -> viewModel -> viewController
-- model - содрежит в себе все raw данные и хранит Стейт, так же умеет общаться с базой и сетью (все зависимости должны реализовываться через протокол)
--  viewModel -  подготавливает данные для отображения, так же связывает model c viewController
- должна быть примерно вот такая древовидная структура в проекте:
-Flows
--Settings
---SettingsModel
---SettingsViewModel
---SettingsViewController
--Answers
---AnswersModel
---AnswersViewModel
---AnswersViewController
-Services
…
-Managers
...
-Resources

2021-11-17 21:37 UTC, MykytaKh commented
Пофиксил. Проверьте пожалуйста.

2021-11-18 18:48 UTC, ios-school-yalantis approved these changes
Нужно пофиксить комменты и можно мерджить!

2021-11-18 18:48 UTC, ios-school-yalantis commented on 8-Ball/8-Ball/Flows/Settings/SettingsView.swift
> +    var settingsVM: SettingsVM?
Не правильно что вью знает о вьюМодели контроллера!

есть три способа связать вью модель с вью через контроллер
- делегат
- реактивный подход
- клоужеры

2021-11-18 18:48 UTC, ios-school-yalantis commented on 8-Ball/8-Ball/Flows/Settings/SettingsModel.swift
> +    private var dbService: DBService!
может быть let и не force unwrap

2021-11-18 18:48 UTC, ios-school-yalantis commented on 8-Ball/8-Ball/Flows/Answers/UserDefaultAnswerModel.swift
> +        return DBService().getUserAnswers().randomElement()
скрытая зависимость `DBService()` 
объект должен создаваться извне и прикидываться параметром через инициализатор. 

что бы его можно было в любой момент подменить. С тем что сейчас это не возможно + детали скрыты пока не откроешь файл невозможно понять что в нем происходит.

2021-11-18 18:48 UTC, ios-school-yalantis commented on 8-Ball/8-Ball/Flows/Answers/AnswerModel.swift
> +            return LocalDefaultAnswerModel().answerValue
UserDefaultAnswerModel() и LocalDefaultAnswerModel() скрытые зависимости!

создавай их вне класса и прикидывай через инициализатор!

2021-11-18 18:48 UTC, ios-school-yalantis commented on 8-Ball/8-Ball/Flows/Answers/AnswerModel.swift
> +    AnswerManager(networkService: Network()).fetchAnswer { answer in
скрытая зависимость
 same issue

2021-11-18 18:56 UTC, ios-school-yalantis approved these changes
Нужно поправить комментарии!

2021-11-18 18:56 UTC, ios-school-yalantis commented on 8-Ball/8-Ball/Flows/Answers/AnswerVM.swift
> +
remove spaces

2021-11-18 18:56 UTC, ios-school-yalantis commented on 8-Ball/8-Ball/Flows/Answers/AnswerViewController.swift
> +class AnswerViewController: UIViewController {
ДЛя AnswerViewController нужно добавить viewModel + model!

2021-11-18 18:56 UTC, ios-school-yalantis commented on 8-Ball/8-Ball/Flows/Answers/AnswerView.swift
> +    let answerVM = AnswerVM()
view ничего не должен знать о  viewModel, только контроллер!
view и viewModel общаться собой через контроллер!

возмоны три способа описаны выше

2021-11-20 17:04 UTC, merged